spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/MovieTicketBooking"
      auto-index-creation: true
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
springdoc:
  pathsToMatch: /, /api/**
